version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: products_db
      MYSQL_USER: usuario_app
      MYSQL_PASSWORD: clave_app
    volumes:
      - db_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d

  app:
    build: .
    ports:
      - "8084:80"
      - "80:80"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: products_db
      DB_USER: usuario_app
      DB_PASS: clave_app

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8085:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
      - db

volumes:
  db_data:
  db_data_local:
  db_data_dev: